postgres:
  host: localhost
  port: 5432
  user: user
  password: pass
  dbname: db_name
  sslmode: disable

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

tasks:
  - name: sync_customer_map
    table: customers
    alias: customer_map
    structure: map
    key: customer_id
    value: display_name
    schedule: "@every 5m"

  - name: sync_order_stream
    table:
    alias: order_stream
    structure: stream
    key_prefix: order_stream
    fields: [order_id, amount, created_at]
    column_map:
      order_id: id
      amount: total
      created_at: timestamp
    schedule: "0 * * * *"