postgres:
  host: localhost
  port: 5432
  user: checker
  password: checker
  dbname: db_checker
  sslmode: disable

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

tasks:
  - name: sync_clients
    table: client_management.t_client
    alias: clients
    structure: map
    key: s_id_client
    value: s_name
    schedule: "@every 1m"
    tracking:
      column: id_client
      operator: ">"
      last_value_key: checkpoint:sync_clients