apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-courier
  namespace: red-courier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: red-courier
  template:
    metadata:
      labels:
        app: red-courier
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
        - name: red-courier
          # Image published by the workflow (latest sha/tag)
          image: ghcr.io/REPLACE_OWNER/REPLACE_REPO:latest
          imagePullPolicy: IfNotPresent
          command: ["./red-courier"]
          workingDir: /app
          envFrom:
            - secretRef:
                name: red-courier-secrets
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: red-courier-config